### ISSUE TITLE
[BUG] 版本号一直有小蓝点，即使在最新版

### ISSUE THREAD

**Issue by EaglePPP** [chatboxai/chatbox#1161]
**Bug Description**
Please provide a clear and concise description of what the bug is.
版本号一直有小蓝点，即使在最新版。无法去掉，逼死强迫症
**Steps to Reproduce**
Please provide the steps to reproduce the bug:
打开软件，看左下角关于
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.
点击以后，如果是最新版小蓝点消失
**Actual Results**
Please provide a clear and concise description of what actually happened.
小蓝点不会消失
**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: Win11&iOS
-   Application Version: 1.22

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

**Comment by 7788jay** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/7473436/e9498f27-bcf1-419d-98cb-690ce6f68b81)
在官网重新下载，看他的版本已经是1.2.4
