### ISSUE TITLE
[Feature] Read one or multiple files

### ISSUE THREAD

**Issue by trymeouteh** [chatboxai/chatbox#1214]
**Problem Description**
Unable to add files to the prompt

**Proposed Solution**
A button that can add one or more files to the prompt which can be submitted with the prompt

**Additional Context**
When using Ollama models, there is no option to send files and there are models that support this in Ollama such as llava

**Comment by mlepeshkin** [comment]
File attachment feature for OpenAI models is super needed.

**Comment by mahomedh** [comment]
This feature has been available since version 1.3.4 https://chatboxai.app/help-center/changelog so I think this issue can be closed now?

**Comment by mlepeshkin** [comment]
For me it's about OpenAI's API. And in cuvvent v. 1.3.12 it's not implemented. When I'm trying to attach files I'm getting: "The current model gpt-4o does not support sending files. Currently supported models: Chatbox AI 4."

**Comment by dmanresa-saes** [comment]
I am experiencing the same issue. I have tried with versions 1.3.4, 1.3.10, and 1.3.14 and I always get the same message. I tested version 1.3.4 with GPT-4 because GPT-4o did not support it yet, but it gives the same error.

**Comment by alanfwilliams** [comment]
This issue still exists. When will file upload for 4o be implemented?

**Comment by phammer** [comment]
Hi there,

is there any update on the topic? Image upload works, but no other file type. Would be great to see this working.

Thanks so much for the great client and also taking this issue up!

**Comment by Bin-Huang** [comment]
Please try updating to v1.6.0. In this version, I've added local parsing and uploading for text and code files. This should be really helpful for anyone using their own API key.
