### ISSUE TITLE
[BUG] 最新模型o1-mini报错

### ISSUE THREAD

**Issue by wgetnz** [chatboxai/chatbox#1529]
**Bug 描述**
使用最新模型o1-mini，api报错，

API Error: Status Code 400, {"error":{"message":"Unsupported value: 'messages[0].role' does not support 'system' with this model. (request id: 20240913101345686242474lX9F6ISn) (request id: 20240913101345687183184ga2S0Aoj)","type":"invalid_request_error","param":"messages[0].role","code":"unsupported_value"}}

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
配置自定义模型o1-mini，保存，删除或者使用默认对话提示，均返回如下错误
API Error: Status Code 400, {"error":{"message":"Unsupported value: 'messages[0].role' does not support 'system' with this model. (request id: 20240913101345686242474lX9F6ISn) (request id: 20240913101345687183184ga2S0Aoj)","type":"invalid_request_error","param":"messages[0].role","code":"unsupported_value"}}

**Comment by gaiar** [comment]
Same with `o1-preview`

**Comment by easychen** [comment]
这个报错的原因是 o1-preview 的接口目前就不支持 system message 和 stream … 
The reason for this error is that the o1-preview API currently does not support system messages and streams

**Comment by huaerss** [comment]
要等作者新版本兼容了
