### ISSUE TITLE
[用户的对话在右边，助手的对话在左边]

### ISSUE THREAD

**Issue by chaojiakeji** [chatboxai/chatbox#328]
**问题描述**
现在用户发出对话，和助手的回答都在左边，不能很快很直观的区分出来，容易混淆

**解决思路**
希望用户的在右边，答案在左边，要是能允许设置用户头像更好了
或者用户对话的底色和助手对话的底色区分一下，方便快速区分。

**Comment by NanTeng** [comment]
+1

**Comment by 96xiaopang** [comment]
复议

**Comment by 1414894911** [comment]
复议+1

**Comment by hcllmsx** [comment]
复议+1

**Comment by Bin-Huang** [comment]
头像设置的功能已经实现了，试试最新的版本。😉😉
消息气泡的风格有开发计划。
