### ISSUE TITLE
利用初步支持安卓。

### ISSUE THREAD

**Issue by Tlntin** [chatboxai/chatbox#811]
目前tauri 2.0已经初步支持安卓，我拿本项目改了一下，参考教程（我写的）：https://www.http5.cn/index.php/archives/22/
运行效果（演示手机系统为：安卓12/鸿蒙3.0 手机：荣耀30）：

https://github.com/Bin-Huang/chatbox/assets/28218658/724ba4b9-aaa5-46c0-80a1-dc85bc1ec957

已知bug:
配置文件无法保存（因为2.0有些api还不支持）

开源链接：https://github.com/Tlntin/tauri_demo

**Comment by Bin-Huang** [comment]
很棒的尝试！对了，各个手机型号、系统版本的兼容情况怎么样？我比较顾虑这个方面，这也是我犹豫那么久的原因。毕竟 tauri v2 还在 beta 阶段……

**Comment by lninghaha** [comment]
我是用edge浏览器桌面快捷的方式弄得，我觉得这个方式也可以

**Comment by Bin-Huang** [comment]
是很棒的尝试，期待有更多设备的实验。目前我对 Chatbox 官方 Android 版本的技术架构还是偏向传统保守的方案，即使在桌面版，Tauri 在很多方面也让我不太满意……

**Comment by tuskermanshu** [comment]
学习了
