### ISSUE TITLE
达到限制token自动清理

### ISSUE THREAD

**Issue by Creativelf** [chatboxai/chatbox#83]
- 能否设置自动清理（可以设置一个阀值，比如过了3000 token，清理最早的问答)这样能多联系上下文）

**Comment by Bin-Huang** [comment]
其实 Chatbox 会自动帮你处理上下文，之前存在一个bug可能会导致答非所问，现在已经修复了。

更新下载：
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.2.1
