### ISSUE TITLE
[ChatBox一键部署功能]

### ISSUE THREAD

**Issue by Formyselfonly** [chatboxai/chatbox#848]
[一键部署功能](https://github.com/Formyselfonly/chatbox-vercel-deploy-oneclick)

**Comment by myworksfun** [comment]
_If you don't do business, why deploy this thing? Isn't the client good?❓_

**Comment by Bin-Huang** [comment]
I tried it out and it seems that the deployment was not successful yet?

我试了一下，似乎还不能部署成功？
