### ISSUE TITLE
[Feature]Add Claude API custom domain option

### ISSUE THREAD

**Issue by lucky-beans** [chatboxai/chatbox#985]
**Problem Description**
AI provider have begun offering Claude API with private domains.

**Proposed Solution**
So Chatbox needs to add the custom domain option of the Claude API.

**Additional Context**
![image](https://github.com/Bin-Huang/chatbox/assets/18460367/2a0c0931-d2e6-460d-9bb6-59ec5820b191)

**Comment by Bin-Huang** [comment]
This feature has been implemented, try the latest version.
